version: '3.8'

services:
  redis:
    container_name: agentic-redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - agentic-seek-net

  searxng:
    container_name: agentic-searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    volumes:
      - ./searxng:/etc/searxng:rw,z
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080/
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - redis
    networks:
      - agentic-seek-net

  backend:
    container_name: agentic-backend
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    restart: unless-stopped
    shm_size: 2g
    volumes:
      - ./workspace:/app/workspace
      - ./screenshots:/app/.screenshots
      - ./config.ini:/app/config.ini
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - SEARXNG_URL=http://searxng:8080
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
      - LM_STUDIO_URL=${LM_STUDIO_URL:-http://host.docker.internal:1234}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - searxng
    networks:
      - agentic-seek-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    container_name: agentic-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.prod
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - agentic-seek-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    container_name: agentic-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./screenshots:/var/www/screenshots
    depends_on:
      - frontend
      - backend
    networks:
      - agentic-seek-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis-data:
  chrome_profiles:

networks:
  agentic-seek-net:
    driver: bridge