version: '3.8'

services:
  redis:
    container_name: redis-prod
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - redis-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - agentic-seek-net

  searxng:
    container_name: searxng-prod
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY:-$(openssl rand -hex 32)}
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - redis
    networks:
      - agentic-seek-net

  backend:
    container_name: backend-prod
    build:
      context: ./
      dockerfile: Dockerfile.production
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./workspace:/app/workspace
      - ./screenshots:/app/.screenshots
    environment:
      - ENVIRONMENT=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - SEARXNG_URL=http://searxng:8080
    depends_on:
      - redis
      - searxng
    networks:
      - agentic-seek-net

  frontend:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - agentic-seek-net

volumes:
  redis-data:

networks:
  agentic-seek-net:
    driver: bridge