apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        command: ["valkey-server", "--save", "30", "1", "--loglevel", "warning"]
        securityContext:
          capabilities:
            drop: [ALL]
            add: [SETGID, SETUID, DAC_OVERRIDE]
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc